@startgantt
Project starts 2023-05-02
[Value-Sim-Data on eder namespace] starts 2023-05-02 and lasts 14 days
[correct diagrams for visualisation] starts 2023-05-16 and lasts 14 days
[Realtime Data on Dashboard + click] starts 2023-05-30 and lasts 14 days
[at least 3 boxes spread across HTL] starts 2023-06-13 and lasts 14 days
@endgantt



